version: '3'
services:
  mongodb-local:
    container_name: mongodb-local
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=codeb
      - MONGO_INITDB_ROOT_PASSWORD=timelogger
    # ports:
    #   - 27017:27017
    restart: unless-stopped
    volumes:
      - dbdata:/data/db

  timelogger-backend:
    container_name: timelogger-backend
    image: codebdocker/timelogger-backend-exe
    ports:
      - 8080:8080
    environment:
      - DB_URL=mongodb://codeb:timelogger@mongodb-local:27017/timelogger-prod?authSource=admin
      - COGNITO_USER_POOL_ID=
      - COGNITO_CLIENT_ID=
      - AWS_REGION=ap-south-1
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - S3_BUCKET=
    links:
      - mongodb-local
    depends_on:
      - mongodb-local
    restart: unless-stopped
  timelogger-admin:
    container_name: timelogger-admin
    image: codebdocker/timelogger-admin
    ports:
      - 3000:80
    restart: unless-stopped

volumes:
  dbdata:
