AWSTemplateFormatVersion: 2010-09-09
Description: for task trackre cloud setup.
Parameters:
  ServiceName:
    Type: String
    Default: timelogger-client
Resources:
  CognitoUserPool:
    Type: "AWS::Cognito::UserPool"
    Properties:
      MfaConfiguration: "OFF"
      UserPoolName: !Join ["", [!Ref ServiceName, -user-pool]]
      UsernameAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: False
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: False
          RequireNumbers: False
          RequireSymbols: False
          RequireUppercase: False
      Schema:
        - Name: email
          Required: true
          Mutable: true
        - Name: name
          Required: true
          Mutable: true
        - Name: phoneNumber
          AttributeDataType: String
          Mutable: true
        - Name: organisationId
          AttributeDataType: String
          Mutable: true
        - Name: role
          AttributeDataType: String
          Mutable: true
        - Name: color
          AttributeDataType: String
          Mutable: true
        - Name: dailyReport
          AttributeDataType: String
          Mutable: true
        - Name: adminReport
          AttributeDataType: String
          Mutable: true
      AccountRecoverySetting:
        RecoveryMechanisms:
        - Name: verified_email
          Priority: 1


  CognitoUserPoolClient:
    Type: "AWS::Cognito::UserPoolClient"
    Properties:
      ClientName: !Join ["", [!Ref ServiceName, -user-pool-client]]
      GenerateSecret: False
      UserPoolId:
        Ref: CognitoUserPool
      AccessTokenValidity: 1
      IdTokenValidity: 1
      TokenValidityUnits:
        AccessToken: days
        IdToken: days
      PreventUserExistenceErrors: ENABLED
      EnableTokenRevocation: False

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      # BucketName: !Ref ServiceName  
      PublicAccessBlockConfiguration:
          BlockPublicAcls: True
          BlockPublicPolicy: True
          IgnorePublicAcls: True
          RestrictPublicBuckets: True
    
Outputs:
  S3BucketPath:
    Value: !GetAtt Bucket.DomainName
  CognitoUserPoolID:
    Value: !GetAtt CognitoUserPool.ProviderName
  CognitoUserPoolClientID:
    Value: !Ref CognitoUserPoolClient
